#!/usr/bin/env python

import os
import sys

if len(sys.argv) == 1:
    print "You must supply an argument!"
    sys.exit(1)

path = sys.argv[1]

if os.path.exists(path):
    print "%s\t%s" % (path, os.path.getsize(path))
else:
    print "Path %s does not exist!" % path
